### ISSUE TITLE
Import the AWS Lambda 'Mind Travel Thumbnail' function Deployment Package

### ISSUE THREAD

**Issue by maximeMD** [maximeMD/mind-travel-api#10]
# User story
**As a** developer
**I want to** have access to the 'Mind Travel Thumbnail' Lambda function source code, and some documentation
**In order to** implement my own Lambda function for my app instance
# Subtasks
- [ ] Export the Deployment Package from the AWS Lambda function
- [ ] Import it in the mind-travel-api git repository
- [ ] Write some documentation on how to implement it and set the triggers between the Lambda function, the S3 buckets and the CloudWatch logs
