### ISSUE TITLE
Write Unit Tests to cover the current source code

### ISSUE THREAD

**Issue by maximeMD** [maximeMD/mind-travel-api#13]
# User story
**As a** developer
**I want to** have unit tests to cover every part of the application
**In order to** avoid regressions as much as possible
# Subtasks
- [ ] Install Jest and Enzyme
- [ ] Write Unit Tests
- [ ] Have at least a 80% code coverage value
