### ISSUE TITLE
Make a production-ready build workflow

### ISSUE THREAD

**Issue by maximeMD** [maximeMD/mind-travel-api#18]
# User story
**As a** developer
**I want to** build correctly my app with 'npm run build'
**In order to** get in the /dist folder a production-ready code
# Subtasks
- [ ] Set resolveJsonModule to false in tsconfig.json in order to exclude it from the build
- [ ] Update the config.json and credentials.json files in order to use them without the resolveJsonModule set to true
- [ ] Update the npm run build script in package.json
