### ISSUE TITLE
Create different users levels (admin, regular user, ...)

### ISSUE THREAD

**Issue by maximeMD** [maximeMD/mind-travel-api#6]
# User story
**As an** administrator 
**I want to** have specials rights on the app
**In order to** be able to do specific actions that the regular user cannot achieve
# Subtasks
- [ ] Create a 'Users' model which will define the user properties retrieved from the database
- [ ] Update the POST /users route in order to define if the newly created user level (administrator or a regular user)
- [ ] Send back the user level in the POST /users/authenticate response body
- [ ] Create an express middleware which will check if the current user is an administrator
- [ ] Set the express middleware in following existing route : POST /users
