### ISSUE TITLE
Set a Jenkinsfile template instead of the current Jenkinsfile files

### ISSUE THREAD

**Issue by maximeMD** [maximeMD/mind-travel-api#8]
# User story
**As a** developer
**I want to** have access to a Jenkinsfile template, and know how to configure my Jenkins instance
**In order to** deliver my own instance of the app
# Subtasks
- [ ] Update the current Jenkinsfile to set environment-related parameters as environment variables
- [ ] Update the maxmd.xyz Jenkins instance to run the updated Jenkinsfile
- [ ] Document the Jenkins pipeline configuration
