### ISSUE TITLE
Create a DynamoDB database for albums

### ISSUE THREAD

**Issue by maximeMD** [maximeMD/mind-travel-api#9]
# User story
**As a**  developer
**I want to** have access to a JSON document for each album
**In order to** get informations about the album, included : album name, thumbnail image, owner, ...
# Subtasks
- [ ] Create a 'mind-travel-albums' table in DynamoDB
- [ ] Set the 'awsDynamoDbTableUsers' property in the credentials.json files  
- [ ] Create a route for album creation (POST /albums)
- [ ] Insert into the DynamoDB table a new document on album creation, specifying the new album informations, which are :
   - name: string
   - thumbnailPictureKey: string
   - owner: string
- [ ] Send the albums informations on GET /albums method
